plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.5' apply false
	id 'io.spring.dependency-management' version '1.1.7' apply false
}

allprojects {
	group = 'com.bouncenet'
	version = '0.0.1-SNAPSHOT'

	repositories {
		mavenCentral()
	}
}

ext {
	springBootDeps = [
		'org.springframework.boot:spring-boot-starter-data-jpa',
		'org.springframework.boot:spring-boot-starter-hateoas',
		'org.springframework.boot:spring-boot-starter-webmvc',
		'org.springframework.boot:spring-boot-starter-web',
		'org.springframework.cloud:spring-cloud-starter-config',
		'com.fasterxml.jackson.core:jackson-databind',
		'org.springframework.boot:spring-boot-starter-validation',
		'org.flywaydb:flyway-core',
		'org.flywaydb:flyway-database-postgresql'
	]

	testDeps = [
		'org.springframework.boot:spring-boot-starter-data-jpa-test',
		'org.springframework.boot:spring-boot-starter-hateoas-test',
		'org.springframework.boot:spring-boot-starter-webmvc-test'
	]
}

subprojects {
	apply plugin: 'java'

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(25)
		}
	}

	tasks.named('test') {
		useJUnitPlatform()
	}
}

configure(subprojects.findAll { it.name != 'payment-service-schema' }) {
	apply plugin: 'io.spring.dependency-management'

	dependencyManagement {
		imports {
			mavenBom "org.springframework.boot:spring-boot-dependencies:4.0.5"
			mavenBom "org.springframework.cloud:spring-cloud-dependencies:2025.1.1"
		}
	}

	dependencies {
		implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
		compileOnly 'org.projectlombok:lombok'
		annotationProcessor 'org.projectlombok:lombok'
		runtimeOnly 'org.postgresql:postgresql'
		testCompileOnly 'org.projectlombok:lombok'
		testAnnotationProcessor 'org.projectlombok:lombok'
		testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	}
}
