razorpay:
  razor-pay-id: rzp_test_SYyYQe3FWpovsd
  razor-pay-secret: 8YU37fUnot5WDScMRIVQBOzH

  webhook:
    webhookUrl: https://bouncenet-payment.loca.lt
    webhookSecret: webhook_secret123

# ssh tunneling for webhook
# ssh -R 80:localhost:9700 serveo.net